#define AREACELL                  4
#define CHISQMIN                  1e-5
#define CLUTPERCCELL              0.5
#define DBZCELL                   15.0
#define DBZCLUTTER                -10.0
#define DBZMAX                    20.0
#define DBZMIN                    -100.0
#define FRINGEDIST                5000.0
#define NBINSGAP                  8
#define NDBZMIN                   25
#define NEIGHBORS                 5
#define NOBSGAPMIN                5
#define NTEXBINAZIM               3
#define NTEXBINRANG               3
#define NTEXMIN                   4
#define REFRACTIVE_INDEX_OF_WATER 0.964
#define SIGMABIRD                 11.0
#define STDEVCELL                 5.0
#define STDEVBIRD                 2.0
#define VDIFMAX                   10.0
#define VRADMIN                   1.0
